version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
         name: Run Lora GWlib
         command: |
           echo 'start to build Lora Gateway'
           make all
           
      - run:
         name: Run Lora GWlib
         command: |
           mkdir -p output
           cp -a libloragw ./output/
           cp -a util_pkt_logger ./output/
           cp -a util_spi_stress ./output/
           cp -a util_tx_test ./output/
           cp -a util_lbt_test ./output/
           cp -a util_tx_continuous ./output/
           cp -a util_spectral_scan ./output/

      - store_artifacts:
          path: /home/circleci/project/output

      - deploy:
          name: Deploy
          command: |
            git push heroku sequential-branch-filter:master

           
           
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter

