version: 2
jobs:
  build:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout

      - run:
         name: Make All Lora GWlib
         command: |
           echo 'start to build Lora Gateway'
           make all
           
      - run:
         name: Copy Lora GWlib to Output
         command: |
           mkdir -p output
           cp -a libloragw/libloragw.a ./output/
           cp -a util_pkt_logger/util_pkt_logger ./output/
           cp -a util_spi_stress/util_spi_stress ./output/
           cp -a util_tx_test/util_tx_test ./output/
           cp -a util_lbt_test/util_lbt_test ./output/
           cp -a util_tx_continuous/util_tx_continuous ./output/
           cp -a util_spectral_scan/util_spectral_scan ./output/
           cp -a ./output ./artifacts
           FILE_LIST=`ls ./artifacts/`
           echo "FILE: $FILE_LIST "
           
      - store_artifacts:
          path: /home/circleci/project/artifacts

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            echo " STEP2 EXEC ls " 
            FILE_LIST=`ls ./artifacts/`
            echo " STEP3 FILE: $FILE_LIST " 
            pwd       
            echo " STEP4 EXEC ghr "
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} v5.0 ./artifacts
            echo " STEP5 WORKING OK "

            
            
            
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              only: master

