version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
         name: Make All Lora GWlib
         command: |
           echo 'start to build Lora Gateway'
           make all
           
      - run:
         name: Copy Lora GWlib to Output
         command: |
           mkdir -p output
           cp -a libloragw ./output/
           cp -a util_pkt_logger ./output/
           cp -a util_spi_stress ./output/
           cp -a util_tx_test ./output/
           cp -a util_lbt_test ./output/
           cp -a util_tx_continuous ./output/
           cp -a util_spectral_scan ./output/
           cp -a ./output ./artifacts
      - store_artifacts:
          path: /home/circleci/project/artifacts

  publish-github-release:
    docker:
      - image: circleci/golang:1.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go version
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} v5.0 ./artifacts/
            echo " ghr TEST ok "
            ls ./artifacts/
            echo " ls TEST ok"
            
            
            
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              only: master

